namespace RYZECHo;

internal sealed partial class GameModel
{
    private static Dictionary<WeaponType, WeaponStats> CreateWeaponStats()
    {
        return new Dictionary<WeaponType, WeaponStats>
        {
            [WeaponType.Blitz] = new()
            {
                Type = WeaponType.Blitz,
                Label = "ブリッツ / 高速連射 SMG",
                ShortLabel = "ブリッツ",
                Code = "BLZ",
                Category = "近距離特化",
                VisionClass = "狭",
                Cost = 220,
                MagazineAmmo = 25,
                ReserveAmmo = 50,
                VisionRange = 220f,
                HearingMultiplier = 1.25f,
                FireCooldown = 0.09f,
                Damage = 7f,
                MoveSpeed = 234f,
                ProjectileRange = 210f,
                ScopedFov = false,
            },
            [WeaponType.Monster] = new()
            {
                Type = WeaponType.Monster,
                Label = "モンスター / 装弾数特化 SMG",
                ShortLabel = "モンスター",
                Code = "MON",
                Category = "近距離特化",
                VisionClass = "中",
                Cost = 310,
                MagazineAmmo = 40,
                ReserveAmmo = 80,
                VisionRange = 300f,
                HearingMultiplier = 1.1f,
                FireCooldown = 0.11f,
                Damage = 8f,
                MoveSpeed = 220f,
                ProjectileRange = 225f,
                ScopedFov = false,
            },
            [WeaponType.Melt] = new()
            {
                Type = WeaponType.Melt,
                Label = "メルト / 高火力 SG",
                ShortLabel = "メルト",
                Code = "MLT",
                Category = "近距離特化",
                VisionClass = "狭",
                Cost = 260,
                MagazineAmmo = 6,
                ReserveAmmo = 12,
                VisionRange = 205f,
                HearingMultiplier = 0.95f,
                FireCooldown = 0.58f,
                Damage = 34f,
                MoveSpeed = 214f,
                ProjectileRange = 122f,
                ScopedFov = false,
            },
            [WeaponType.Fairy] = new()
            {
                Type = WeaponType.Fairy,
                Label = "フェアリー / 軽量 AR",
                ShortLabel = "フェアリー",
                Code = "FAR",
                Category = "中距離バランス",
                VisionClass = "中",
                Cost = 350,
                MagazineAmmo = 30,
                ReserveAmmo = 60,
                VisionRange = 330f,
                HearingMultiplier = 1f,
                FireCooldown = 0.17f,
                Damage = 13f,
                MoveSpeed = 224f,
                ProjectileRange = 315f,
                ScopedFov = false,
            },
            [WeaponType.Giant] = new()
            {
                Type = WeaponType.Giant,
                Label = "ジャイアント / 安定重視 AR",
                ShortLabel = "ジャイアント",
                Code = "GNT",
                Category = "中距離バランス",
                VisionClass = "中",
                Cost = 400,
                MagazineAmmo = 30,
                ReserveAmmo = 90,
                VisionRange = 340f,
                HearingMultiplier = 0.95f,
                FireCooldown = 0.21f,
                Damage = 16f,
                MoveSpeed = 210f,
                ProjectileRange = 332f,
                ScopedFov = false,
            },
            [WeaponType.Juggernaut] = new()
            {
                Type = WeaponType.Juggernaut,
                Label = "ジャガーノート / 制圧型 LMG",
                ShortLabel = "ジャガーノート",
                Code = "JGN",
                Category = "中距離バランス",
                VisionClass = "中",
                Cost = 560,
                MagazineAmmo = 100,
                ReserveAmmo = 100,
                VisionRange = 320f,
                HearingMultiplier = 0.88f,
                FireCooldown = 0.12f,
                Damage = 11f,
                MoveSpeed = 188f,
                ProjectileRange = 336f,
                ScopedFov = false,
            },
            [WeaponType.Violet] = new()
            {
                Type = WeaponType.Violet,
                Label = "ヴァイオレット / 軽量 SR",
                ShortLabel = "ヴァイオレット",
                Code = "VLT",
                Category = "遠距離特化",
                VisionClass = "極大",
                Cost = 470,
                MagazineAmmo = 5,
                ReserveAmmo = 10,
                VisionRange = 470f,
                HearingMultiplier = 0.75f,
                FireCooldown = 0.62f,
                Damage = 34f,
                MoveSpeed = 192f,
                ProjectileRange = 420f,
                ScopedFov = false,
            },
            [WeaponType.Changer] = new()
            {
                Type = WeaponType.Changer,
                Label = "チェンジャー / 一撃重視 SR",
                ShortLabel = "チェンジャー",
                Code = "CHG",
                Category = "遠距離特化",
                VisionClass = "極大",
                Cost = 620,
                MagazineAmmo = 5,
                ReserveAmmo = 5,
                VisionRange = 500f,
                HearingMultiplier = 0.7f,
                FireCooldown = 0.85f,
                Damage = 52f,
                MoveSpeed = 176f,
                ProjectileRange = 460f,
                ScopedFov = false,
            },
            [WeaponType.Howl] = new()
            {
                Type = WeaponType.Howl,
                Label = "ハウル / セミオート DMR",
                ShortLabel = "ハウル",
                Code = "HWL",
                Category = "遠距離特化",
                VisionClass = "大",
                Cost = 430,
                MagazineAmmo = 15,
                ReserveAmmo = 30,
                VisionRange = 390f,
                HearingMultiplier = 0.82f,
                FireCooldown = 0.24f,
                Damage = 19f,
                MoveSpeed = 205f,
                ProjectileRange = 375f,
                ScopedFov = false,
            },
            [WeaponType.Pulse] = new()
            {
                Type = WeaponType.Pulse,
                Label = "パルス / 安定型 HG",
                ShortLabel = "パルス",
                Code = "PLS",
                Category = "サブウェポン",
                VisionClass = "中",
                Cost = 90,
                MagazineAmmo = 12,
                ReserveAmmo = 36,
                VisionRange = 260f,
                HearingMultiplier = 1.05f,
                FireCooldown = 0.24f,
                Damage = 12f,
                MoveSpeed = 238f,
                ProjectileRange = 230f,
                ScopedFov = false,
            },
            [WeaponType.Shard] = new()
            {
                Type = WeaponType.Shard,
                Label = "シャード / 速射型 HG",
                ShortLabel = "シャード",
                Code = "SHD",
                Category = "サブウェポン",
                VisionClass = "中",
                Cost = 130,
                MagazineAmmo = 18,
                ReserveAmmo = 54,
                VisionRange = 250f,
                HearingMultiplier = 1.1f,
                FireCooldown = 0.18f,
                Damage = 9f,
                MoveSpeed = 244f,
                ProjectileRange = 215f,
                ScopedFov = false,
            },
        };
    }

}
